DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from DjangoBlog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from DjangoBlog.feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from DjangoBlog.admin_site import admin_site
from django.urls import include, path

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
    url(r'^admin/', admin_site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'', include('comments.urls', namespace='comment')),
    url(r'', include('accounts.urls', namespace='account')),
    url(r'', include('oauth.urls', namespace='oauth')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^feed/$', DjangoBlogFeed()),
    url(r'^rss/$', DjangoBlogFeed()),
    url(r'^search', include('haystack.urls'), name='search'),
    url(r'', include('servermanager.urls', namespace='servermanager')),
    url(r'', include('owntracks.urls', namespace='owntracks'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2016/11/2 下午7:15
"""

from django.urls import path
from django.views.decorators.cache import cache_page
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView

app_name = "blog"
urlpatterns = [
    path(
        r'',
        views.IndexView.as_view(),
        name='index'),
    path(
        r'page/<int:page>/',
        views.IndexView.as_view(),
        name='index_page'),
    path(
        r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    path(
        r'category/<slug:category_name>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail'),
    path(
        r'category/<slug:category_name>/<int:page>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail_page'),
    path(
        r'author/<author_name>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail'),
    path(
        r'author/<author_name>/<int:page>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail_page'),
    path(
        r'tag/<slug:tag_name>.html',
        views.TagDetailView.as_view(),
        name='tag_detail'),
    path(
        r'tag/<slug:tag_name>/<int:page>.html',
        views.TagDetailView.as_view(),
        name='tag_detail_page'),
    path(
        'archives.html',
        cache_page(
            60 * 60)(
            views.ArchivesView.as_view()),
        name='archives'),
    path(
        'links.html',
        views.LinkListView.as_view(),
        name='links'),
    path(
        r'upload',
        views.fileupload,
        name='upload'),
    path(
        r'refresh',
        views.refresh_memcache,
        name='refresh')]

comments/DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from DjangoBlog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from DjangoBlog.feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from DjangoBlog.admin_site import admin_site
from django.urls import include, path

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
    url(r'^admin/', admin_site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'', include('comments.urls', namespace='comment')),
    url(r'', include('accounts.urls', namespace='account')),
    url(r'', include('oauth.urls', namespace='oauth')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^feed/$', DjangoBlogFeed()),
    url(r'^rss/$', DjangoBlogFeed()),
    url(r'^search', include('haystack.urls'), name='search'),
    url(r'', include('servermanager.urls', namespace='servermanager')),
    url(r'', include('owntracks.urls', namespace='owntracks'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/share_layout/adsense.html
<aside id="text-2" class="widget widget_text"><h3 class="widget-title">Google AdSense</h3>
    <div class="textwidget">

        {{ GOOGLE_ADSENSE_CODES }}
    </div>
</aside>

templates/share_layout/analyticscode.html
<script type="text/javascript">
    (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-27354903-4', 'auto');
    ga('send', 'pageview');
    var _hmt = _hmt || [];
    (function () {
        var hm = document.createElement("script");
        hm.src = "https://hm.baidu.com/hm.js?30dd00aec5f76607ba37c6770ae48e45";
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(hm, s);
    })();
</script>
<a href="https://tongji.baidu.com/sc-web/3478620/home/ico?siteId=11261596" target="_blank" rel="nofollow">百度统计</a>

templates/share_layout/base.html
{% load static %}
{% load cache %}
{% load compress %}
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" lang="zh-CN" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" lang="zh-CN" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<![endif]-->
<!--[if !(IE 7) & !(IE 8)]><!-->
<html lang="zh-CN" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<!--<![endif]-->
<head>

        <!--google  ad -->
         <script data-ad-client="ca-pub-2762414263954067" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>

         <meta charset="UTF-8"/>
         <meta http-equiv="X-UA-Compatible" content="IE=edge">
         <meta name="description" content="cxx1.com原创博客网站、Django建站、数学、物理、化学、第一原创网。打造中国第一原创博客网，第一python博客，原创第一、博客第一">
         <meta name="keywords" content="python、php、java、网站工具、站长、博客、数学、Django、mdeditor、c哩c哩、C++、C#、C语言、流程图、机器学习、人工智能、网站建设、Markdown、原创、Django、Markdown、editormd、原创、seo、C++、c#、单片机、人工智能、机器学习、大数据、云计算、阿里云、腾讯云、百度、Google、阿里巴巴、华为">

        <!--百度验证-->
         <meta name="domain_verify" content="pmrgi33nmfuw4ir2ejrxq6brfzrw63jcfqrgo5ljmqrduitemq3tcmtgguzdsmtbmu2gemdcheztkzjzhfrtozrygbrtozdfgarcyitunfwwku3bozsseorrgu4tiobxha2dcobvheyh2">

        <!--百度验证-->
         <meta name="baidu_union_verify" content="4795476678203ce8f6ac6135afe6863f">

        <!--Google验证-->
         <meta name="google-site-verification" content="1AoImeiqjMfPbFsL1ZG6kq11BFzOqukwlCJzYfaZSj8" />

        <!--百度统计-->
         <meta name="baidu-site-verification" content="cb2bzjC3Uo" />

        <!--分辨率适应-->
         <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes" />

         <meta name="renderer" content="webkit">

         <meta http-equiv="Cache-Control" content="no-siteapp"/>

         <meta name="format-detection" content="telephone=no">

         <meta name="mobile-web-app-capable" content="yes">
         <meta name="apple-mobile-web-app-capable" content="yes">
         <meta name="apple-mobile-web-app-status-bar-style" content="black">
         <meta name="apple-mobile-web-app-title" content="cxx1.com 原创博客第一网"/>



    {% block header %}
    {% endblock %}

    <link rel="profile" href="http://gmpg.org/xfn/11"/>

    <!--图标-->
    <link rel="icon" href="{% static 'blog/img/favicon.ico' %}">
    <link rel="icon" href="{% static 'bg/css/normalize.css' %}">
    <link rel="icon" href="{% static 'bg/css/bg.css' %}">
    <link rel="icon" href="{% static 'bg/css/component.css' %}">
    <!--[if lt IE 9]>
    <script src="{% static 'blog/js/html5.js' %}" type="text/javascript"></script>
    <![endif]-->

    <link rel="alternate" type="application/rss+xml" title="{{ SITE_NAME }} &raquo; Feed" href="/feed"/>

    {% compress css %}

     <link rel='stylesheet' id='twentytwelve-fonts-css' href="{% static 'blog/fonts/fonts.css' %}" type='text/css' media='all'/>
     <link rel='stylesheet' id='twentytwelve-style-css' href="{% static 'blog/css/style.css' %}" type='text/css' media='all'/>
     <link href="{% static 'blog/css/oauth_style.css' %}" rel="stylesheet">
     <link rel="stylesheet" href="{% static 'mdeditor/css/editormd.preview.css' %}">
     <link rel="stylesheet" href="{% static 'mdeditor/css/editormd.min.css' %}">

    {% comment %}

        <!--cnd -->

        <script data-ad-client="ca-pub-2762414263954067" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
        <script src="https://cdn.bootcss.com/bootstrap/3.2.0/js/transition.js"></script>
        <!-- 压缩版本 -->
          <!--引入three.js三维引擎-->
        <!--<script src="http://www.yanhuangxueyuan.com/versions/threejsR92/build/three.js"></script>-->
          <!-- <script src="./three.js"></script> -->
        <!--<script src="http://www.yanhuangxueyuan.com/threejs/build/three.js"></script>-->




    {% endcomment %}
        <!--[if lt IE 9]>
        <link rel='stylesheet' id='twentytwelve-ie-css'  href="{% static 'blog/css/ie.css' %}" type='text/css' media='all' />
        <![endif]-->
        <!--<link rel="stylesheet" href="{% static 'assets/css/bg.css' %}">-->
        <link rel="stylesheet" href="{% static 'pygments/default.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/nprogress.css' %}">

        <!-- Live 2d for css-->
        <link rel="stylesheet" href="{% static 'live2D/waifu.min.css' %}">

        <!-- amazeui for css -->
        <link rel="stylesheet" href="{% static 'assets/css/amazeui.min.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/app.css' %}">

        <!-- mdeditor for css -->
        <link rel="stylesheet" href="{% static 'mdeditor/css/editormd.preview.css' %}">
        <link rel="stylesheet" href="{% static 'mdeditor/css/editormd.min.css' %}">


        <!--zoom for css-->
        <link rel="stylesheet" href="{% static 'zoom/css/zoom.css' %}">



        <!--layer for css-->
        <link rel="stylesheet" href="{% static 'layer/theme/default/layer.css' %}">

        <!--share for css-->
        <link rel="stylesheet" href="{% static 'share/css/share.min.css' %}">


        {% block compress_css %}
        {% endblock %}
    {% endcompress %}



<body >

<!--google 广告-->
<script type='text/javascript'>
    (function(a, b, c, d, e, j, s) {
        a[d] = a[d] || function() {
            (a[d].a = a[d].a || []).push(arguments)
        };
        j = b.createElement(c),
            s = b.getElementsByTagName(c)[0];
        j.async = true;
        j.charset = 'UTF-8';
        j.src = 'https://static.meiqia.com/widget/loader.js';
        s.parentNode.insertBefore(j, s);
    })(window, document, 'script', '_MEIQIA');
    _MEIQIA('entId', 240757);
</script>



<!--[if lte IE 9]>
<p class="browsehappy">你正在使用<strong>过时</strong>的浏览器，Amaze UI 暂不支持。 请 <a
  href="http://browsehappy.com/" target="_blank">升级浏览器</a>
  以获得更好的体验！</p>
<![endif]-->


<div class="container demo-1">
<div class="blog large-header" id="large-header" >
        <canvas id="demo-canvas" style="position:absolute;z-index:-999;"></canvas>
        <header class="am-g am-g-fixed blog-fixed blog-text-center blog-header">

            <div class="am-u-sm-8 am-u-sm-centered">

                <img width="200" src="/blog/static/blog/img/logo3.jpg" alt="Amaze UI Logo"/>
                <h2 class="am-hide-sm-only">{{ SITE_NAME }}</h2>
            </div>
        </header>

        {% cache 36000 nav %}
            {% include 'share_layout/nav.html' %}
        {% endcache %}

                 <div  id="main" >
                 <div  class="am-u-md-8">

                    {% block content %}

                    {% endblock %}
                </div>
        {% block sidebar %}

        {% endblock %}

    </div>

    {% include 'share_layout/footer.html' %}

</div><!-- #blog -->

</div>
</body>
<footer>
    {% compress js %}
        <script type="text/javascript" src="{% static 'blog/js/jquery-3.1.1.js' %}"></script>

        <!--背景星空图-->
        <script type="text/javascript" src="{% static 'bg/js/TweenLite.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'bg/js/EasePack.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'bg/js/rAF.js' %}"></script>
        <script type="text/javascript" src="{% static 'bg/js/bg.js' %}"></script>

        <script type="text/javascript" src="{% static 'blog/js/nprogress.js' %}"></script>
        <script src="{% static 'blog/js/blog.js' %}" type="application/javascript"></script>
        <script src="{% static 'blog/js/navigation.js' %}" type="application/javascript"></script>
    <!-- live2D for js -->
        <script src="{% static 'live2D/jquery.min.js' %}"></script>
        <script src="{% static 'live2D/jquery-ui.min.js' %}"></script>
        <script src="{% static 'live2D/waifu-tips.min.js' %}"></script>
        <script src="{% static 'live2D/live2d.min.js' %}"></script>

    <!-- AmazeUI for is -->
        <script src="{% static 'assets/js/amazeui.min.js' %}"></script>
        <!--[if lt IE 9]>
        <script src="http://cdn.staticfile.org/modernizr/2.8.3/modernizr.js"></script>
        <script src="{% static 'assets/js/amazeui.ie8polyfill.min.js' %}"></script>
        <![endif]-->


        <script  src="{% static 'layer/layer.js' %}"></script>

    <!-- mdeditor for js -->
        <script src="{% static 'mdeditor/editormd.js' %}"></script>
        <script src="{% static 'mdeditor/lib/marked.min.js' %}"></script>
        <script src="{% static 'mdeditor/lib/raphael.min.js' %}"></script>
        <script src="{% static 'mdeditor/lib/underscore.min.js' %}"></script>
        <script src="{% static 'mdeditor/lib/sequence-diagram.min.js' %}"></script>
        <script src="{% static 'mdeditor/lib/prettify.min.js' %}"></script>
        <script src="{% static 'mdeditor/lib/flowchart.min.js' %}"></script>
        <script src="{% static 'mdeditor/lib/jquery.flowchart.min.js' %}"></script>
        <script src="{% static 'assets/js/mdeditor.setting.js' %}"></script>

        <script src="{% static 'threejs/three.min.js' %}"></script>

        <!--share for js-->

        <script src="{% static 'share/js/social-share.js' %}"></script>
        <script src="{% static 'share/js/qrcode.js' %}"></script>
        <script src="{% static 'share/js/share.setting.js' %}"></script>

       <!--zoom for js-->
        <script src="{% static 'zoom/js/zoom.js' %}"></script>
        <script>

                $("img").attr("data-action","zoom")

                if($('img').attr('id') != 'logo-had'){
                    $("img").addClass("am-img-thumbnail am-radius")
                }

                 // $("img").click(function() {
                 //        $("img").addClass("am-fl")
                 //    }) //添加浮动

        </script>

    <!--live2D的模型参数-->
        <script>
               /* 可直接修改部分参数 */
              /* 可直接修改部分参数 */
        live2d_settings['modelId'] = 2;                  // 默认模型 ID
        live2d_settings['modelTexturesId'] = 87;         // 默认材质 ID
        live2d_settings['modelStorage'] = true;         // 不储存模型 ID
        live2d_settings['canCloseLive2d'] = true;       // 隐藏 关闭看板娘 按钮
        live2d_settings['canTurnToHomePage'] = false;    // 隐藏 返回首页 按钮
        live2d_settings['waifuSize'] = '200x250';        // 看板娘大小
        live2d_settings['waifuTipsSize'] = '150x50';    // 提示框大小
        live2d_settings['waifuFontSize'] = '15px';       // 提示框字体
        live2d_settings['waifuToolFont'] = '20px';       // 工具栏字体
        live2d_settings['waifuToolLine'] = '25px';       // 工具栏行高
        live2d_settings['waifuToolTop'] = '-60px';       // 工具栏顶部边距
        live2d_settings['waifuDraggable'] = 'unlimited';    // 拖拽样式, 随便放
        live2d_settings['waifuEdgeSide'] = 'left:900';       //放在左边
        live2d_settings['waifuDraggableRevert'] = false;    //松开鼠标还原拖拽位置

        /* 在 initModel 前添加 */
        initModel("/blog/static/live2D/waifu-tips.json")


        </script>




    {% block compress_js %}
        {% endblock %}
    {% endcompress %}
    {% block footer %}
    {% endblock %}
</footer>



</html>

templates/share_layout/base_account.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="baidu_union_verify" content="21cf2099dc891d837ca4a540f1044f2a">
    <meta name="robots" content="noindex">
    <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    {% load compress %}
    {% compress css %}

        <link rel="icon" href="{% static 'blog/img/favicon.ico' %}">
        <!-- Bootstrap core CSS -->
        <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'blog/css/oauth_style.css' %}" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="{% static 'assets/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
        <!-- TODC Bootstrap core CSS -->
        <link href="{% static 'assets/css/todc-bootstrap.min.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'assets/css/signin.css' %}" rel="stylesheet">
        <!-- Live2D for this css-->
         <!--<link href="{% static 'live2D/waifu.min.css' %}" rel="stylesheet">-->
         <!-- amazeui for css -->
   


    {% endcompress %}
    {% compress js %}
        <script src="{% static 'assets/js/ie10-viewport-bug-workaround.js' %}"></script>
        <script src="{% static 'assets/js/ie-emulation-modes-warning.js' %}"></script>




    {% endcompress %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


    <![endif]-->
</head>

<body>
{% block content %}
{% endblock %}

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

</body>
</html>

templates/share_layout/footer.html
<footer id="colophon" role="contentinfo">

    <div class="site-info" style="text-align: center">
        Copyright&copy;&nbsp;{{ CURRENT_YEAR }}&nbsp;
        <a href="/" target="blank">{{ SITE_NAME }}</a>
        &nbsp;|&nbsp;
        <a href="/sitemap.xml" title="SiteMap" target="_blank">
            SiteMap
        </a>
        &nbsp;|&nbsp;
        <a href="/feed" title="RSS Feed" target="_blank">
            RSS Feed
        </a>
        &nbsp;|&nbsp;
        <a href="/links.html" title="友情链接" rel="nofollow" target="_blank">
            友情链接
        </a>
        |&nbsp;
        <script>
            var _hmt = _hmt || [];
            (function() {
              var hm = document.createElement("script");
              hm.src = "https://hm.baidu.com/hm.js?d5c3c886e0cbed57dd8dd7aaa1f841b9";
              var s = document.getElementsByTagName("script")[0];
              s.parentNode.insertBefore(hm, s);
            })();
            </script>
        <a href="https://tongji.baidu.com/sc-web/3478620/home/ico?siteId=11261596" target="_blank"
           rel="nofollow">百度统计</a>

        {% comment %}{% include 'share_layout/analyticscode.html' %}{% endcomment %}
        |
        <script type="text/javascript">document.write(unescape("%3Cspan id='cnzz_stat_icon_1279058550'%3E%3C/span%3E%3Cscript src='https://v1.cnzz.com/z_stat.php%3Fid%3D1279058550%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>
    </div>
    <div class="site-info" style="text-align: center">
        Powered by
        <a href="https://www.djangoproject.com/" rel="nofollow" target="blank">Django</a>
        &nbsp;|&nbsp;
        <a href="https://github.com/whitexiong/DjangoBlog" rel="nofollow" target="blank">whitexiong</a>
        |
        <a href="http://www.cxx1.com" target="blank">white</a>
    </div>
    {% if BEIAN_CODE %}
        <div class="site-info" style="text-align: center">
            <a href="http://www.beian.miit.gov.cn/" rel="nofollow" target="_blank">
                <p style=" height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">
                    {{ BEIAN_CODE }}
                </p>
            </a>
            {% if BEIAN_CODE_GONGAN and SHOW_GONGAN_CODE %}
                {{ BEIAN_CODE_GONGAN |safe }}
            {% endif %}
        </div>



    {% endif %}
    {% if ANALYTICS_CODE %}
        {{ ANALYTICS_CODE| safe }}
    {% endif %}

</footer><!-- #colophon -->

templates/share_layout/nav.html

<nav id="site-navigation" class="main-navigation" data-am-sticky role="navigation">
    <button class="menu-toggle">菜单</button>



    <a class="assistive-text" href="#content" title="跳至正文">跳至正文</a>




    <div class="menu-%e8%8f%9c%e5%8d%95-container" style="background:#eedeff; color:#FFF">
        <ul id="menu-%e8%8f%9c%e5%8d%95" class="nav-menu">
            <li id="menu-item-3498"
                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-3498">
                <a href="/">首页</a></li>

                    {% load blog_tags %}
                    {% query nav_category_list parent_category=None as root_categorys %}
                    {% for node in root_categorys %}
                        {% include 'share_layout/nav_node.html' %}
                    {% endfor %}
                    {% if nav_pages %}
                        {% for node in nav_pages %}

                    <li id="menu-item-{{ node.pk }}"
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-{{ node.pk }}">
                        <a href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                    </li>
                {% endfor %}
            {% endif %}
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                <a href="{% url "blog:archives" %}">文章归档</a>
            </li>


        </ul>

    </div>

</nav><!-- #site-navigation -->



<div id="moble-nav" style="display: none">
<nav class="am-g am-g-fixed blog-fixed blog-nav">
<button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only blog-button" data-am-collapse="{target: '#blog-collapse'}" ><span class="am-sr-only">导航切换</span> <span class="am-icon-bars"></span></button>

  <div class="am-collapse am-topbar-collapse" id="blog-collapse">
    <ul class="am-nav am-nav-pills am-topbar-nav">
       <li id="menu-item-3498"
                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-3498">
                <a href="/">首页</a></li>
      <li class="am-dropdown" data-am-dropdown>

           {% load blog_tags %}
                    {% query nav_category_list parent_category=None as root_categorys %}
                    {% for node in root_categorys %}
                        {% include 'share_layout/nav_node.html' %}
                    {% endfor %}
                    {% if nav_pages %}
                        {% for node in nav_pages %}

                         <li id="menu-item-{{ node.pk }}"
                        class="menu-item-{{ node.pk }}">
                        <a href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                    </li>
                 {% endfor %}
            {% endif %}

      </li>
         <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                <a href="{% url "blog:archives" %}">文章归档</a>
         </li>
    </ul>


  </div>
</nav>
    </div>

templates/share_layout/nav_node.html
<li id="menu-item-{{ node.pk }}"
    class="menu-item-{{ node.pk }}">
    <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
    {% load blog_tags %}
    {% query nav_category_list parent_category=node as child_categorys %}
    {% if child_categorys %}

        <ul class="sub-menu">
            {% for child in child_categorys %}
                {% with node=child template_name="share_layout/nav_node.html" %}
                    {% include template_name %}
                {% endwith %}
            {% endfor %}

        </ul>
    {% endif %}
</li>