DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from DjangoBlog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from DjangoBlog.feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from DjangoBlog.admin_site import admin_site
from django.urls import include, path

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
    url(r'^admin/', admin_site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'', include('comments.urls', namespace='comment')),
    url(r'', include('accounts.urls', namespace='account')),
    url(r'', include('oauth.urls', namespace='oauth')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^feed/$', DjangoBlogFeed()),
    url(r'^rss/$', DjangoBlogFeed()),
    url(r'^search', include('haystack.urls'), name='search'),
    url(r'', include('servermanager.urls', namespace='servermanager')),
    url(r'', include('owntracks.urls', namespace='owntracks'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2016/11/20 下午3:52
"""

from django.conf.urls import url
from django.contrib.auth import views as auth_view
from django.urls import path
from . import views
from .forms import LoginForm

app_name = "accounts"

urlpatterns = [url(r'^login/$',
                   views.LoginView.as_view(success_url='/'),
                   name='login',
                   kwargs={'authentication_form': LoginForm}),
               url(r'^register/$',
                   views.RegisterView.as_view(success_url="/"),
                   name='register'),
               url(r'^logout/$',
                   views.LogoutView.as_view(),
                   name='logout'),
               path(r'account/result.html',
                    views.account_result,
                    name='result')]

blog/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2016/11/2 下午7:15
"""

from django.urls import path
from django.views.decorators.cache import cache_page
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView

app_name = "blog"
urlpatterns = [
    path(
        r'',
        views.IndexView.as_view(),
        name='index'),
    path(
        r'page/<int:page>/',
        views.IndexView.as_view(),
        name='index_page'),
    path(
        r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    path(
        r'category/<slug:category_name>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail'),
    path(
        r'category/<slug:category_name>/<int:page>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail_page'),
    path(
        r'author/<author_name>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail'),
    path(
        r'author/<author_name>/<int:page>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail_page'),
    path(
        r'tag/<slug:tag_name>.html',
        views.TagDetailView.as_view(),
        name='tag_detail'),
    path(
        r'tag/<slug:tag_name>/<int:page>.html',
        views.TagDetailView.as_view(),
        name='tag_detail_page'),
    path(
        'archives.html',
        cache_page(
            60 * 60)(
            views.ArchivesView.as_view()),
        name='archives'),
    path(
        'links.html',
        views.LinkListView.as_view(),
        name='links'),
    path(
        r'upload',
        views.fileupload,
        name='upload'),
    path(
        r'refresh',
        views.refresh_memcache,
        name='refresh')]

comments/DjangoBlog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from DjangoBlog.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from DjangoBlog.feeds import DjangoBlogFeed
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.conf.urls.static import static
from DjangoBlog.admin_site import admin_site
from django.urls import include, path

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'
urlpatterns = [
    url(r'^admin/', admin_site.urls),
    url(r'', include('blog.urls', namespace='blog')),
    url(r'mdeditor/', include('mdeditor.urls')),
    url(r'', include('comments.urls', namespace='comment')),
    url(r'', include('accounts.urls', namespace='account')),
    url(r'', include('oauth.urls', namespace='oauth')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^feed/$', DjangoBlogFeed()),
    url(r'^rss/$', DjangoBlogFeed()),
    url(r'^search', include('haystack.urls'), name='search'),
    url(r'', include('servermanager.urls', namespace='servermanager')),
    url(r'', include('owntracks.urls', namespace='owntracks'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

owntracks/urls.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: urls.py
@time: 2018/2/25 下午3:04
"""
from django.urls import path
from . import views

app_name = "owntracks"

urlpatterns = [
    path('owntracks/logtracks', views.manage_owntrack_log, name='logtracks'),
    path('owntracks/show_maps', views.show_maps, name='show_maps'),
    path('owntracks/get_datas', views.get_datas, name='get_datas'),
    path('owntracks/show_dates', views.show_log_dates, name='show_dates')
]

comments/models.py
from django.db import models
from django.conf import settings
from blog.models import Article
from django.utils.timezone import now


# Create your models here.

class Comment(models.Model):
    body = models.TextField('正文', max_length=300)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='作者',
        on_delete=models.CASCADE)
    article = models.ForeignKey(
        Article,
        verbose_name='文章',
        on_delete=models.CASCADE)
    parent_comment = models.ForeignKey(
        'self',
        verbose_name="上级评论",
        blank=True,
        null=True,
        on_delete=models.CASCADE)
    is_enable = models.BooleanField(
        '是否显示', default=True, blank=False, null=False)

    class Meta:
        ordering = ['id']
        verbose_name = "评论"
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def __str__(self):
        return self.body

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

blog/forms.py
#!/usr/bin/env python
# encoding: utf-8


"""
@version: ??
@author: liangliangyy
@license: MIT Licence
@contact: liangliangyy@gmail.com
@site: https://www.lylinux.net/
@software: PyCharm
@file: forms.py
@time: 2017/1/7 上午12:36
"""

from haystack.forms import SearchForm
from django import forms
import logging

logger = logging.getLogger(__name__)


class BlogSearchForm(SearchForm):
    querydata = forms.CharField(required=True)

    def search(self):
        datas = super(BlogSearchForm, self).search()
        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['querydata']:
            logger.info(self.cleaned_data['querydata'])
        return datas

templates/blog/tags/article_info.html
{% load blog_tags %}
{% load cache %}
<article id="post-{{ article.pk }} "
         class="post-{{ article.pk }} post type-post status-publish format-standard hentry">


    <header class="entry-header">
        <div data-am-widget="titlebar" class="am-titlebar am-titlebar-default" >
        <hr class="entry-title">
            {% if  isindex %}
                {% if article.article_order > 0 %}
                    <h2 class="am-titlebar-title">
                    <a href="{{ article.get_absolute_url }}"
                       rel="bookmark">【置顶】{{ article.title }}</a>
                        </h2>
                {% else %}

                    <h2 class="am-titlebar-title">
                    <a href="{{ article.get_absolute_url }}"
                       rel="bookmark">{{ article.title }}</a>
                    </h2>
                {% endif %}

            {% else %}
                {{ article.title }}
            {% endif %}
        </hr>
        </div>

        <div class="comments-link">
            {% if article.comment_status == "o" and open_site_comment %}
                <a href="{{ article.get_absolute_url }}#comments" class="ds-thread-count" data-thread-key="3815"
                   rel="nofollow">
                    <span class="leave-reply">
                    {% if article.comment and article.comment_set.count %}
                        {{ article.comment_set.count }}个评论
                    {% else %}
                        发表评论
                    {% endif %}
                    </span>
                </a>
            {% endif %}
            <div style="float:right">
                {{ article.views }} views
            </div>
        </div><!-- .comments-link -->
        <br/>
        {% if article.type == 'a' %}
            {% if not isindex %}
                {% cache 36000 breadcrumb article.pk %}
                    {% load_breadcrumb article %}
                {% endcache %}
            {% endif %}
        {% endif %}
    </header><!-- .entry-header -->
    <ol>
    <div  class="entry-content" itemprop="articleBody">

        {% if  isindex %}
            {{ article.body|custom_markdown|escape|truncatechars_content }}
                <p class='read-more'><a
                    href=' {{ article.get_absolute_url }}'>Read more</a>
                </p>

        {% else %}
                 <div id="test-editormd-view" class="">
                         <textarea style="display:none; " >
                            {{ article.body }}
                         </textarea>
                 </div>
        {% endif %}

    </div><!-- .entry-content -->

    {% load_article_metas article user %}

</article><!-- #post -->

templates/blog/tags/article_meta_info.html
{% load blog_tags %}
{% load cache %}
{% with article.id|add:user.is_authenticated as cachekey %}
    {% cache 36000 metainfo cachekey %}
        <footer class="entry-meta">
            本条目发布于<a href="{{ article.get_absolute_url }}" title="{% datetimeformat article.pub_time %}"
                     itemprop="datePublished" content="{% datetimeformat article.pub_time %}"
                     rel="bookmark">

            <time class="entry-date updated"
                  datetime="{{ article.pub_time }}">
                {% datetimeformat article.pub_time %}</time>
        </a>
            {% if article.type == 'a' %}
                。属于<a href="{{ article.category.get_absolute_url }}" rel="category tag">{{ article.category.name }}</a>
                分类，
                {% if article.tags.all %}
                    被贴了

                    {% for t in article.tags.all %}
                        <a href="{{ t.get_absolute_url }}" rel="tag">{{ t.name }}</a>
                        {% if t != article.tags.all.last %}
                            ，
                        {% endif %}
                    {% endfor %}

                    标签。
                {% endif %}
            {% endif %}
            <span class="by-author">作者是
        <span class="author vcard">
            <a class="url fn n" href="{{ article.author.get_absolute_url }}"
               title="查看所有由{{ article.author.username }}发布的文章"
               rel="author">
            <span itemprop="author" itemscope itemtype="http://schema.org/Person">

            <span itemprop="name" itemprop="publisher">

            {{ article.author.username }}
        </span>
            </span>
    </a>
        </span>。
                {% if user.is_superuser %}
                    <a href="{{ article.get_admin_url }}">编辑</a>
                {% endif %}
    </span>


            <div id="share-2"></div>
        </footer><!-- .entry-meta -->

    {% endcache %}
{% endwith %}

templates/blog/tags/article_pagination.html
<nav id="nav-below" class="navigation" role="navigation">
    <h3 class="assistive-text">文章导航</h3>
    {% if page_obj.has_next  and next_url%}
        <div class="nav-previous"><a
                href="{{ next_url }}"><span
                class="meta-nav">&larr;</span> 早期文章</a></div>
    {% endif %}
    {% if page_obj.has_previous and previous_url %}
        <div class="nav-next"><a href="{{ previous_url }}">较新文章
            <span
                    class="meta-nav">→</span></a>
        </div>
    {% endif %}
</nav><!-- .navigation -->

templates/blog/tags/article_tag_list.html
{% if article_tags_list %}
    <div class="panel panel-default">
        <div class="panel-heading">标签</div>
        <div class="panel-body">

            {% for url,count,tag,color in article_tags_list %}
                <a class="label label-{{ color }}" style="display: inline-block;" href="{{ url }}"
                   title="{{ tag.name }}">
                    {{ tag.name }}
                    <span class="badge">{{ count }}</span>
                </a>
            {% endfor %}

        </div>
    </div>
{% endif %}

templates/blog/tags/breadcrumb.html
<div class="breadcrumb am-icon-home">
    {% for name,url in names %}
        <div itemscope itemtype="http://data-vocabulary.org/Breadcrumb">

            <a href="{{ url }}" itemprop="url">

                <span itemprop="title"> {{ name }}</span>

            </a>&nbsp;&rsaquo;

        </div>
    {% endfor %}
    {{ title }}
</div>

templates/blog/tags/sidebar.html
{% load blog_tags %}




    <div id="secondary"  class="am-u-md-4 blog-sidebar" role="complementary">

        <div class="am-panel-group" id="accordion">
          <div class="am-panel am-panel-primary">
            <div class="am-panel-hd">
              <h4 class="am-panel-title" data-am-collapse="{parent: '#accordion', target: '#do-not-say-1'}">
                 <label class="screen-reader-text" for="s">搜索：</label>
              </h4>
            </div>
            <div id="do-not-say-1" class="am-panel-collapse am-collapse am-in">
              <div class="am-panel-bd">

                    <form role="search" method="get" id="searchform" class="am-topbar-form am-topbar-left am-form-inline am-topbar-right" action="/search">
                        <div class="am-form-group">

                            <input  class="am-form-field am-input-lg" type="text" placeholder="搜索文章" value="" name="q" id="q"/>
                            <input type="submit" class="am-btn am-btn-default" id="searchsubmit" value="搜索"/>
                        </div>
                    </form>

                    <br>
                    <br>
              </div>
            </div>
        </div>


     <div class="am-panel-group" id="accordion2">

        <section class="am-panel am-panel-default ">
    {% if extra_sidebars %}
                {% for sidebar in extra_sidebars %}

                <div class="am-panel-hd" data-am-collapse="{parent: '#accordion2', target: '#do-not-say-2'}">

                    {{ sidebar.name }} (点击关闭)
                </div>
            <div id="do-not-say-2" class="am-panel-collapse am-collapse am-in">
                <div class="am-panel-bd">
                    <p>
                    {{ sidebar.content|custom_markdown }}
                    </p>
                    <a class="am-btn am-btn-success am-btn-sm" href="#">查看更多 →</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
            </section>
    {% if most_read_articles %}
        <section class="am-panel am-panel-default">
            <div class="am-panel-hd">Views</div>
            <ul class="am-list blog-list">
                {% for a in most_read_articles %}
                    <li>
                        <a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                            {{ a.title }}
                        </a> - {{ a.views }} views
                    </li>
                {% endfor %}
            </ul>

        </section>
    {% endif %}
    {% if sidebar_categorys %}
            <section class="am-panel am-panel-default">
            <div class="am-panel-hd">分类目录</div>
            <ul class="am-list am-list-border">
                {% for c in sidebar_categorys %}
                    <li class="cat-item cat-item-184"><a href={{ c.get_absolute_url }}>{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
            </section>
    {% endif %}
    {% if sidebar_comments and  open_site_comment %}

        <section class="am-panel am-panel-success">
            <div class="am-panel-hd">近期评论</div>
            {% comment %}
                <div class="am-panel-bd">
                <ul class="am-list blog-list" data-num-items="5" data-show-avatars="1" data-show-time="1"
                    data-show-title="1" data-show-admin="1" data-avatar-size="30" data-excerpt-length="70">
                </ul>{% endcomment %}
                 <ul id="recentcomments" class="am-list am-list-border">
                {% for c in sidebar_comments %}
                    <li class="recentcomments">
                        <span style="float: left" class="am-badge am-badge-secondary am-round">{{ c.author.username }}</span> 发表了评论 :
                        <i class="am-icon-comment-o am-icon-fw"></i><a class="am-text-truncate" href="{{ c.article.get_absolute_url }}#comment-{{ c.pk }}">{{ c.article.title }}</a>
                    </li>

                {% endfor %}
                </ul>
                </div>

        </section>
    {% endif %}
    {% if recent_articles %}
        <section class="am-panel am-panel-default">
            <div class="am-panel-hd">近期文章</div>
            <ul class="am-list am-list-border">

                {% for a in  recent_articles %}
                    <li><a href="{{ a.get_absolute_url }}" title="{{ a.title }}">
                        {{ a.title }}
                    </a></li>
                {% endfor %}
            </ul>
        </section>
    {% endif %}
    {% if sidabar_links %}
        <section class="am-panel am-panel-secondary">
            <div class="am-panel-hd">书签</div>
            <ul class='am-list am-list-border'>
                {% for l in sidabar_links %}
                    <li>
                        <a href="{{ l.link }}" target="_blank" title="{{ l.name }}"><i class="am-icon-tag am-icon-fw"></i>{{ l.name }}</a>
                    </li>
                {% endfor %}

            </ul>
        </section>
    {% endif %}
    {% if show_google_adsense %}
        <section class="am-panel am-panel-default">
                <div class="am-panel-hd">广告推广</div>
                 <div class="am-panel-bd">
                {{ google_adsense_codes|safe }}
                </div>
        </section>
    {% endif %}
    {% if sidebar_tags %}

          <div style="margin-top: 5%;" class="blog-clear-margin blog-sidebar-widget blog-bor am-g ">
            <h2 class="blog-title"><span>TAG cloud</span></h2>
            <div class="am-u-sm-12 blog-clear-padding">

                 {% for tag,count,size in sidebar_tags %}
                    <a href="{{ tag.get_absolute_url }}"
                       class="tag-link-{{ tag.id }} tag-link-position-{{ tag.id }} blog-tag"
                       style="font-size: {{ size }}pt;" title="{{ count }}个话题"> {{ tag.name }}
                    </a>
                {% endfor %}

            </div>
          </div>

    {% endif %}
    <!--<aside id="text-2" class="widget widget_text"><h3 class="widget-title">欢迎您star或者fork本站源代码</h3>-->
        <!--<div class="textwidget">-->

            <!--<p><a href="https://github.com/liangliangyy/DjangoBlog" rel="nofollow"><img-->
                    <!--src="https://resource.lylinux.net/img.shields.io/github/stars/liangliangyy/djangoblog.svg?style=social&amp;label=Star"-->
                    <!--alt="GitHub stars"></a> <a href="https://github.com/liangliangyy/DjangoBlog" rel="nofollow"><img-->
                    <!--src="https://resource.lylinux.net/img.shields.io/github/forks/liangliangyy/djangoblog.svg?style=social&amp;label=Fork"-->
                    <!--alt="GitHub forks"></a></p>-->
        <!--</div>-->
    <!--</aside>-->


    <section class="am-panel am-panel-danger">
        <div class="am-panel-hd">功能</div>
        <ul class="am-list blog-list">
            <li><a href="/admin/" rel="nofollow">管理站点</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url "account:logout" %}" rel="nofollow">登出</a>
                </li>

            {% else %}
                <li><a href="{% url "account:login" %}" rel="nofollow">登录</a>
            {% endif %}
            {% if user.is_superuser %}
                <li><a href="{% url "blog:refresh" %}" target="_blank">刷新缓存</a></li>
                <!--<li><a href="{% url 'owntracks:show_dates' %}" target="_blank">运动轨迹记录</a></li>-->
            {% endif %}
            <!--<li><a href="http://gitbook.lylinux.net" target="_blank" rel="nofollow">GitBook</a></li>-->
        </ul>
    </section>
    <div id="rocket" class="show" title="点我返回顶部"></div>
    </div>
</div><!-- #secondary -->